name: CI
on: [push, pull_request]

jobs:
#   build-linux-gcc:
#   runs-on: ubuntu-18.04
#   steps:
#     - uses: actions/checkout@v1
#     - name: build all and examples
#       run: |
#         make -k
#       env:
#         CC: gcc
#         CXX: g++
# build-linux-clang:
#   runs-on: ubuntu-18.04
#   steps:
#     - uses: actions/checkout@v1
#     - name: build all and examples
#       run: |
#         make -k
#       env:
#         CC: clang
#         CXX: clang++
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build all
        shell: cmd
        # this replaces default PowerShell, which can't fail the build
        run: |
          .\build.bat && powershell -file .\package.ps1
      - name: "Upload zip with binaries"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev-${{ github.run_id }}-${{ github.run_attempt }}"
          prerelease: true
          title: "Handmade Build"
          files: |
            release.zip
