on:
  push:
    branch:
      - "main"

jobs:
  build:
    # Run a job for each of the specified target architectures:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout the sauce 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: MSVC setup
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: MSVC compilation 
        run: |
          ./forge/forge.bat package
      - name: "Upload zip with binaries"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev-${{ github.run_id }}-${{ github.run_attempt }}"
          prerelease: false
          title: "Development Build"
          files: |
            ./releases/*.zip
