on:
  push:
    branch:
      - "main"

jobs:
  build:
    # Run a job for each of the specified target architectures:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout the sauce 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: MSVC setup
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: MSVC compilation 
        run: |
          call dist.bat
      - name: Make zip
        run: |
          Compress-Archive -Force -Path dist\pack -DestinationPath dist\handmade.zip
      - name: "Upload zip with binaries"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev-${{ github.run_id }}-${{ github.run_attempt }}"
          prerelease: true
          title: "Handmade Build"
          files: |
            dist/handmade.zip
